name: restauran
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Supabase
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4

  # UI
  table_calendar: ^3.2.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.6
  pin_code_fields: ^8.0.1

  # Utils & State
  image_picker: ^1.1.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  crypto: ^3.0.6
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.0

  # Notifications
  flutter_local_notifications: ^17.2.0

  # Firebase (полностью совместимые)
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.6
  intl: ^0.20.2
  firebase_admin: ^0.3.1+1
  # Hive — локальная NoSQL БД (офлайн кэш)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager: ^0.9.0+3

  # Отслеживание состояния сети
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
