// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk',
    appId: '1:745460234210:web:2abb562eb32b852fa86bbb',
    messagingSenderId: '745460234210',
    projectId: 'aq-toi',
    authDomain: 'aq-toi.firebaseapp.com',
    databaseURL: 'https://aq-toi-default-rtdb.firebaseio.com',
    storageBucket: 'aq-toi.firebasestorage.app',
    measurementId: 'G-S8YC3BJ63Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jI8VmTobmf-V6AIclwbvmhCS751z1sI',
    appId: '1:745460234210:android:88a4939bdc7bcdf7a86bbb',
    messagingSenderId: '745460234210',
    projectId: 'aq-toi',
    databaseURL: 'https://aq-toi-default-rtdb.firebaseio.com',
    storageBucket: 'aq-toi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm-31XuDa7If_Q-dZSt0wUlaBv6_zEB2c',
    appId: '1:745460234210:ios:b065b0ee2f21888da86bbb',
    messagingSenderId: '745460234210',
    projectId: 'aq-toi',
    databaseURL: 'https://aq-toi-default-rtdb.firebaseio.com',
    storageBucket: 'aq-toi.firebasestorage.app',
    iosBundleId: 'com.daulettuken.blood.moon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm-31XuDa7If_Q-dZSt0wUlaBv6_zEB2c',
    appId: '1:745460234210:ios:32e761b3d5a217e2a86bbb',
    messagingSenderId: '745460234210',
    projectId: 'aq-toi',
    databaseURL: 'https://aq-toi-default-rtdb.firebaseio.com',
    storageBucket: 'aq-toi.firebasestorage.app',
    iosBundleId: 'com.blood.moon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk',
    appId: '1:745460234210:web:2abb562eb32b852fa86bbb',
    messagingSenderId: '745460234210',
    projectId: 'aq-toi',
    authDomain: 'aq-toi.firebaseapp.com',
    databaseURL: 'https://aq-toi-default-rtdb.firebaseio.com',
    storageBucket: 'aq-toi.firebasestorage.app',
    measurementId: 'G-S8YC3BJ63Z',
  );
}