// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcioJoSOzMd2rx0eZYvs7nnptjQhXDk3c',
    appId: '1:895420289220:web:c664d44efe43f97d62b991',
    messagingSenderId: '895420289220',
    projectId: 'restaurant-app-a576e',
    authDomain: 'restaurant-app-a576e.firebaseapp.com',
    storageBucket: 'restaurant-app-a576e.firebasestorage.app',
    measurementId: 'G-RSNPSGT1X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTartpyeI0QcFOQQK3EfdE-seLDsgWow',
    appId: '1:895420289220:android:e0dd95115794d64762b991',
    messagingSenderId: '895420289220',
    projectId: 'restaurant-app-a576e',
    storageBucket: 'restaurant-app-a576e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLPOn5E0xOUdSFY_6nzF8__ZXWlurYdM',
    appId: '1:895420289220:ios:06d97b28306ce8d662b991',
    messagingSenderId: '895420289220',
    projectId: 'restaurant-app-a576e',
    storageBucket: 'restaurant-app-a576e.firebasestorage.app',
    iosBundleId: 'com.blood.moon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKLPOn5E0xOUdSFY_6nzF8__ZXWlurYdM',
    appId: '1:895420289220:ios:06d97b28306ce8d662b991',
    messagingSenderId: '895420289220',
    projectId: 'restaurant-app-a576e',
    storageBucket: 'restaurant-app-a576e.firebasestorage.app',
    iosBundleId: 'com.blood.moon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcioJoSOzMd2rx0eZYvs7nnptjQhXDk3c',
    appId: '1:895420289220:web:82bd914eb65129c962b991',
    messagingSenderId: '895420289220',
    projectId: 'restaurant-app-a576e',
    authDomain: 'restaurant-app-a576e.firebaseapp.com',
    storageBucket: 'restaurant-app-a576e.firebasestorage.app',
    measurementId: 'G-PM7GN2C2JK',
  );
}
