// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk",
      authDomain: "aq-toi.firebaseapp.com",
      projectId: "aq-toi",
      storageBucket: "aq-toi.firebasestorage.app",
      messagingSenderId: "745460234210",
      appId: "1:745460234210:web:41af58acf1ad811fa86bbb",
      measurementId: "G-JMCNSK71E6");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk",
    appId: "1:745460234210:web:41af58acf1ad811fa86bbb",
    messagingSenderId: "745460234210",
    projectId: "aq-toi",
    storageBucket: "aq-toi.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk",
    appId: "1:745460234210:web:41af58acf1ad811fa86bbb",
    messagingSenderId: "745460234210",
    projectId: "aq-toi",
    storageBucket: "aq-toi.firebasestorage.app",
    iosBundleId: 'com.blood.moon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk",
    appId: "1:745460234210:web:41af58acf1ad811fa86bbb",
    messagingSenderId: "745460234210",
    projectId: "aq-toi",
    storageBucket: "aq-toi.firebasestorage.app",
    iosBundleId: 'com.blood.moon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyDtaU-sAzzW-9flDsw4_NpXytiI1WgzIPk",
      appId: "1:745460234210:web:41af58acf1ad811fa86bbb",
      messagingSenderId: "745460234210",
      projectId: "aq-toi",
      authDomain: "aq-toi.firebaseapp.com",
      storageBucket: "aq-toi.firebasestorage.app",
      measurementId: "G-JMCNSK71E6");
}
